name: Weekly Data Cleaning Automation

on:
  schedule:
    - cron: '0 23 * * 1' # Se ejecuta cada Lunes a las 23:00 UTC (7 PM EST/EDT)
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create token cache from secret
        run: echo "${{ secrets.TOKEN_CACHE_BIN_CONTENT }}" > token_cache.bin

      - name: Run the Python script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: python clean_drive_files.py
